version: "1"

services:
  virahesab:
    container_name: virahesab
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000"
    volumes:
      - ./src:/app/src
      - ./public:/app/public
