import type { Metadata } from "next";
import SWRProvider from "@/src/components/providers/SWRProvider";
import localFont from "next/font/local";
import "../src/styles/globals.css";
import { ThemeProvider } from "@/src/components/providers/ThemeProvider";

const ravi = localFont({ src: "../public/fonts/Ravi-VF.ttf" });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={ravi.className}>
        <SWRProvider>
          <ThemeProvider
            attribute="class"
            defaultTheme="system"
            enableSystem
            disableTransitionOnChange
          >
            {children}
          </ThemeProvider>
        </SWRProvider>
      </body>
    </html>
  );
}
