import type { Metadata } from "next";
import SWRProvider from "@/src/components/providers/SWRProvider";
import localFont from "next/font/local";
import "../src/styles/globals.css";

const ravi = localFont({ src: "../public/fonts/Ravi-VF.ttf" });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={ravi.className}>
        <SWRProvider>{children}</SWRProvider>
      </body>
    </html>
  );
}
